name: Run test and publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  # unit_tests:
  #   if: github.event.pull_request.merged == true # Condition
  #   name: Unit Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run Unit Tests
  #       run: npm run test

  # e2e_tests:
  #   name: E2e Test For Core package
  #   needs: unit_tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build test
  #       run: npx lerna run build:test --scope=@thinhnguyen_zsy/core

  #     - name: Run e2e Tests
  #       run: npx lerna run test:e2e --scope=@thinhnguyen_zsy/core

  #     - uses: actions/upload-artifact@v4
  #       name: 'upload artfact'
  #       if: success() || failure()
  #       with:
  #         name: my-artifacts
  #         path: ./packages/core/test/scripts/*.out.txt

  publish:
    if: github.event.pull_request.merged == true # Condition
    name: Publish
    # needs: e2e_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Make changes
        run: |
          echo "Test change" >> file.txt
          git add file.txt
          git commit -m "Update file.txt with test change"

      - name: 'Version and publish'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:develop
